version: "3.0"
services:
  postgres:
    container_name: hello_hardware_postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
  pgadmin:
    container_name: hello_hardware_pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
  redis:
    container_name: hello_hardware_cache
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
      - "${REDIS_INSIGHT_PORT}:${REDIS_INSIGHT_PORT}"
    volumes:
      - ./data/redis/:/data
  elasticsearch:
    container_name: hello_hardware_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - bootstrap.memory_lock=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

volumes:
  esdata:
    driver: local
