/* eslint-disable max-lines */
/* eslint-disable no-console */
import { getRepository } from 'typeorm';
import type { Seeder } from 'typeorm-seeding';
import { Auth } from '../../auth/entities/auth.entity';
import { Category } from '../../category/entities/category.entity';
import type { FilesService } from '../../files/service/file.service';
import { Product } from '../../product/entity/product.entity';
import { Store } from '../../store/entities/store.entity';

const PRODUCTS = [
  // Laptops
  {
    name: 'Lenovo ThinkPad T14 Gen 1 14"',
    brand: 'Lenovo',
    specs: 'Intel Core i5-10310U 16GB RAM 256GB SSD',
    price: 362.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/lenovo-thinkpad.png',
    gallery: 'assets/images/products/lenovo-thinkpad.png',
    galleryImages: [
      'assets/images/products/lenovo-thinkpad.png',
      'assets/images/products/dell-monitor.png',
      'assets/images/products/apple-homepod.png',
      'assets/images/products/dell-latitude.png',
    ],
    features: [
      'Enterprise-grade security',
      'Long battery life (up to 10 hours)',
      'Spill-resistant keyboard',
      'Extensive connectivity options',
    ],
    label: 'SALE',
    labelColor: '#2db224',
    inStock: true,
    active: true,
    description: 'Powerful and reliable business laptop with excellent performance and durability',
    shortDescription: 'Powerful business laptop with excellent performance',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.47kg', displaySize: '14 inches', resolution: '1920x1080' },
  },
  // Laptops
  {
    name: 'Lenovo ThinkPad T14 Gen 1 14"',
    brand: 'Lenovo',
    specs: 'Intel Core i5-10310U 16GB RAM 256GB SSD',
    price: 362.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/lenovo-thinkpad.png',
    gallery: 'assets/images/products/lenovo-thinkpad.png',
    galleryImages: [
      'assets/images/products/lenovo-thinkpad.png',
      'assets/images/products/dell-monitor.png',
      'assets/images/products/apple-homepod.png',
      'assets/images/products/dell-latitude.png',
    ],
    features: [
      'Enterprise-grade security',
      'Long battery life (up to 10 hours)',
      'Spill-resistant keyboard',
      'Extensive connectivity options',
    ],
    label: 'SALE',
    labelColor: '#2db224',
    inStock: true,
    active: true,
    description: 'Powerful and reliable business laptop with excellent performance and durability',
    shortDescription: 'Powerful business laptop with excellent performance',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.47kg', displaySize: '14 inches', resolution: '1920x1080' },
  },
  // Laptops
  {
    name: 'Lenovo ThinkPad T14 Gen 1 14"',
    brand: 'Lenovo',
    specs: 'Intel Core i5-10310U 16GB RAM 256GB SSD',
    price: 362.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/lenovo-thinkpad.png',
    gallery: 'assets/images/products/lenovo-thinkpad.png',
    galleryImages: [
      'assets/images/products/lenovo-thinkpad.png',
      'assets/images/products/dell-monitor.png',
      'assets/images/products/apple-homepod.png',
      'assets/images/products/dell-latitude.png',
    ],
    features: [
      'Enterprise-grade security',
      'Long battery life (up to 10 hours)',
      'Spill-resistant keyboard',
      'Extensive connectivity options',
    ],
    label: 'SALE',
    labelColor: '#2db224',
    inStock: true,
    active: true,
    description: 'Powerful and reliable business laptop with excellent performance and durability',
    shortDescription: 'Powerful business laptop with excellent performance',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.47kg', displaySize: '14 inches', resolution: '1920x1080' },
  },

  // Telephones (Smartphones)
  {
    name: 'Xiaomi Mi 11 Ultra',
    brand: 'Xiaomi',
    specs: '12GB+256GB',
    price: 450.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/xiaomi-mi11.png',
    gallery: 'assets/images/products/xiaomi-mi11.png',
    label: 'NOUVEAU',
    labelColor: '#edd146',
    inStock: true,
    active: true,
    description: 'Flagship smartphone with exceptional camera capabilities and powerful performance',
    shortDescription: 'Selfie periscope for optimal quality',
    categoryName: 'Telephones',
    extraAttributes: { display: '6.81 inches AMOLED', camera: '50MP+48MP+48MP', battery: '5000mAh' },
  },
  {
    name: 'Apple iPhone 13 Pro',
    brand: 'Apple',
    specs: '6GB+256GB',
    price: 799.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/iphone13.png',
    gallery: 'assets/images/products/iphone13.png',
    inStock: true,
    active: true,
    description: 'Premium smartphone with advanced camera system and powerful A15 Bionic chip',
    shortDescription: 'Premium smartphone with advanced camera system',
    categoryName: 'Telephones',
    extraAttributes: { display: '6.1 inches Super Retina XDR', camera: '12MP+12MP+12MP', battery: '3095mAh' },
  },

  // Tablets (using existing smart home devices as placeholders)
  {
    name: 'New Apple Homepod Mini-8',
    brand: 'Apple',
    specs: '100% packed with innovation',
    price: 299.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/apple-homepod.png',
    gallery: 'assets/images/products/apple-homepod.png',
    label: 'NOUVEAU',
    labelColor: '#2da5f3',
    inStock: true,
    active: true,
    description: 'Compact smart device with incredible sound quality and seamless integration with Apple ecosystem',
    shortDescription: 'Beautiful new design',
    categoryName: 'Tablets',
    extraAttributes: { color: 'White', connectivity: 'WiFi, Bluetooth', assistant: 'Siri' },
  },

  // Tablets
  {
    name: 'Apple iPad Pro 12.9"',
    brand: 'Apple',
    specs: '128GB, M2 Chip',
    price: 1099.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/ipad-pro.png',
    gallery: 'assets/images/products/ipad-pro.png',
    label: 'NEW',
    labelColor: '#2da5f3',
    inStock: true,
    active: true,
    description: 'Powerful tablet with M2 chip, stunning Liquid Retina XDR display, and advanced camera system',
    shortDescription: 'Professional-grade tablet for creative work',
    categoryName: 'Tablets',
    extraAttributes: { displaySize: '12.9 inches', resolution: '2732x2048', processor: 'Apple M2' },
  },
  {
    name: 'Samsung Galaxy Tab S8 Ultra',
    brand: 'Samsung',
    specs: '256GB, 5G',
    price: 899.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/samsung-tab-s8.png',
    gallery: 'assets/images/products/samsung-tab-s8.png',
    label: 'TOP SELLER',
    labelColor: '#edd146',
    inStock: true,
    active: true,
    description: 'Massive 14.6" Super AMOLED display, S Pen included, powerful performance for work and play',
    shortDescription: 'Ultimate productivity tablet',
    categoryName: 'Tablets',
    extraAttributes: { displaySize: '14.6 inches', resolution: '2960x1848', connectivity: '5G' },
  },

  // Ecran Plat (Monitors)
  {
    name: 'Dell Monitor',
    brand: 'Dell',
    specs: 'High-resolution display',
    price: 199.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/dell-monitor.png',
    gallery: 'assets/images/products/dell-monitor.png',
    inStock: true,
    active: true,
    description: 'High-quality flat screen monitor for professional and personal use',
    shortDescription: 'Professional-grade flat screen monitor',
    categoryName: 'Ecran Plat',
    extraAttributes: { displaySize: '24 inches', resolution: '1920x1080', panelType: 'IPS' },
  },

  // Laptops
  {
    name: 'Lenovo ThinkPad T14 Gen 1 14"',
    brand: 'Lenovo',
    specs: 'Intel Core i5-10310U 16GB RAM 256GB SSD',
    price: 362.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/lenovo-thinkpad.png',
    gallery: 'assets/images/products/lenovo-thinkpad.png',
    galleryImages: [
      'assets/images/products/lenovo-thinkpad.png',
      'assets/images/products/dell-monitor.png',
      'assets/images/products/apple-homepod.png',
      'assets/images/products/dell-latitude.png',
    ],
    features: [
      'Enterprise-grade security',
      'Long battery life (up to 10 hours)',
      'Spill-resistant keyboard',
      'Extensive connectivity options',
    ],
    label: 'SALE',
    labelColor: '#2db224',
    inStock: true,
    active: true,
    description: 'Powerful and reliable business laptop with excellent performance and durability',
    shortDescription: 'Powerful business laptop with excellent performance',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.47kg', displaySize: '14 inches', resolution: '1920x1080' },
  },
  {
    name: 'HP EliteBook 840 G5 14"',
    brand: 'HP',
    specs: 'Intel Core i5-8350U 16GB RAM 256GB SSD',
    price: 301.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/hp-elitebook.png',
    gallery: 'assets/images/products/hp-elitebook.png',
    inStock: true,
    active: true,
    description: 'Premium business laptop with advanced security features and solid performance',
    shortDescription: 'Premium business laptop with advanced security',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.48kg', displaySize: '14 inches', resolution: '1920x1080' },
  },
  {
    name: 'Dell Latitude 7400 14"',
    brand: 'Dell',
    specs: 'Intel Core i7-8665U 16GB RAM 256GB SSD',
    price: 380.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/dell-latitude.png',
    gallery: 'assets/images/products/dell-latitude.png',
    label: '-25% OFF',
    labelColor: '#2db224',
    inStock: true,
    active: true,
    description: 'Ultra-thin business laptop with exceptional battery life and performance',
    shortDescription: 'Ultra-thin business laptop with exceptional battery life',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.36kg', displaySize: '14 inches', resolution: '1920x1080' },
  },
  {
    name: 'Xiaomi Mi 11 Ultra',
    brand: 'Xiaomi',
    specs: '12GB+256GB',
    price: 450.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/xiaomi-mi11.png',
    gallery: 'assets/images/products/xiaomi-mi11.png',
    label: 'NOUVEAU',
    labelColor: '#edd146',
    inStock: true,
    active: true,
    description: 'Flagship smartphone with exceptional camera capabilities and powerful performance',
    shortDescription: 'Selfie periscope for optimal quality',
    categoryName: 'Smartphones',
    extraAttributes: { display: '6.81 inches AMOLED', camera: '50MP+48MP+48MP', battery: '5000mAh' },
  },
  {
    name: 'New Apple Homepod Mini-8',
    brand: 'Apple',
    specs: '100% packed with innovation',
    price: 299.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/apple-homepod.png',
    gallery: 'assets/images/products/apple-homepod.png',
    label: 'NOUVEAU',
    labelColor: '#2da5f3',
    inStock: true,
    active: true,
    description: 'Compact smart speaker with incredible sound quality and seamless integration with Apple ecosystem',
    shortDescription: 'Beautiful new design',
    categoryName: 'Smart Home',
    extraAttributes: { color: 'White', connectivity: 'WiFi, Bluetooth', assistant: 'Siri' },
  },
  {
    name: 'Apple iPhone 13 Pro',
    brand: 'Apple',
    specs: '6GB+256GB',
    price: 799.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/iphone13.png',
    gallery: 'assets/images/products/iphone13.png',
    inStock: true,
    active: true,
    description: 'Premium smartphone with advanced camera system and powerful A15 Bionic chip',
    shortDescription: 'Premium smartphone with advanced camera system',
    categoryName: 'Smartphones',
    extraAttributes: { display: '6.1 inches Super Retina XDR', camera: '12MP+12MP+12MP', battery: '3095mAh' },
  },
  {
    name: 'Samsung Galaxy S21 Ultra',
    brand: 'Samsung',
    specs: '12GB+256GB',
    price: 749.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/samsung-s21.png',
    gallery: 'assets/images/products/samsung-s21.png',
    label: '-10% OFF',
    labelColor: '#edd146',
    inStock: true,
    active: true,
    description: 'Flagship smartphone with 108MP camera and 120Hz adaptive display',
    shortDescription: 'Flagship smartphone with 108MP camera',
    categoryName: 'Smartphones',
    extraAttributes: { display: '6.8 inches Dynamic AMOLED 2X', camera: '108MP+10MP+10MP+12MP', battery: '5000mAh' },
  },
  {
    name: 'Google Pixel 6 Pro',
    brand: 'Google',
    specs: '12GB+128GB',
    price: 699.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/google-pixel6.png',
    gallery: 'assets/images/products/google-pixel6.png',
    inStock: true,
    active: true,
    description: 'Google flagship with exceptional camera capabilities and the new Tensor chip',
    shortDescription: 'Google flagship with exceptional camera capabilities',
    categoryName: 'Smartphones',
    extraAttributes: { display: '6.7 inches LTPO OLED', camera: '50MP+48MP+12MP', battery: '5003mAh' },
  },
  {
    name: 'Lenovo ThinkPad T14 Gen 1 15"',
    brand: 'Lenovo',
    specs: 'Intel Core i5-10310U 16GB RAM 256GB SSD',
    price: 362.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/lenovo-thinkpad.png',
    gallery: 'assets/images/products/lenovo-thinkpad.png',
    galleryImages: [
      'assets/images/products/lenovo-thinkpad.png',
      'assets/images/products/dell-monitor.png',
      'assets/images/products/apple-homepod.png',
      'assets/images/products/dell-latitude.png',
    ],
    features: [
      'Enterprise-grade security',
      'Long battery life (up to 10 hours)',
      'Spill-resistant keyboard',
      'Extensive connectivity options',
    ],
    label: 'SALE',
    labelColor: '#2db224',
    inStock: true,
    active: true,
    description: 'Powerful and reliable business laptop with excellent performance and durability',
    shortDescription: 'Powerful business laptop with excellent performance',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.51kg', displaySize: '15 inches', resolution: '1920x1080' },
  },
  {
    name: 'HP EliteBook 840 G5 15"',
    brand: 'HP',
    specs: 'Intel Core i5-8350U 16GB RAM 256GB SSD',
    price: 301.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/hp-elitebook.png',
    gallery: 'assets/images/products/hp-elitebook.png',
    inStock: true,
    active: true,
    description: 'Premium business laptop with advanced security features and solid performance',
    shortDescription: 'Premium business laptop with advanced security',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.51kg', displaySize: '15 inches', resolution: '1920x1080' },
  },
  {
    name: 'Dell Latitude 7400 15"',
    brand: 'Dell',
    specs: 'Intel Core i7-8665U 16GB RAM 256GB SSD',
    price: 380.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/dell-latitude.png',
    gallery: 'assets/images/products/dell-latitude.png',
    label: '-25% OFF',
    labelColor: '#2db224',
    inStock: true,
    active: true,
    description: 'Ultra-thin business laptop with exceptional battery life and performance',
    shortDescription: 'Ultra-thin business laptop with exceptional battery life',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.41kg', displaySize: '15 inches', resolution: '1920x1080' },
  },
  {
    name: 'Xiaomi Mi 11 Ultra Pro',
    brand: 'Xiaomi',
    specs: '12GB+256GB',
    price: 450.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/xiaomi-mi11.png',
    gallery: 'assets/images/products/xiaomi-mi11.png',
    label: 'NOUVEAU',
    labelColor: '#edd146',
    inStock: true,
    active: true,
    description: 'Flagship smartphone with exceptional camera capabilities and powerful performance',
    shortDescription: 'Selfie periscope for optimal quality',
    categoryName: 'Smartphones',
    extraAttributes: { display: '6.81 inches AMOLED', camera: '50MP+48MP+48MP', battery: '5000mAh' },
  },
  {
    name: 'New Apple Homepod Mini-7',
    brand: 'Apple',
    specs: '100% packed with innovation',
    price: 299.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/apple-homepod.png',
    gallery: 'assets/images/products/apple-homepod.png',
    label: 'NOUVEAU',
    labelColor: '#2da5f3',
    inStock: true,
    active: true,
    description: 'Compact smart speaker with incredible sound quality and seamless integration with Apple ecosystem',
    shortDescription: 'Beautiful new design',
    categoryName: 'Smart Home',
    extraAttributes: { color: 'White', connectivity: 'WiFi, Bluetooth', assistant: 'Siri' },
  },
  {
    name: 'Lenovo ThinkPad T14 Gen 1 16"',
    brand: 'Lenovo',
    specs: 'Intel Core i5-10310U 16GB RAM 256GB SSD',
    price: 362.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/lenovo-thinkpad.png',
    gallery: 'assets/images/products/lenovo-thinkpad.png',
    galleryImages: [
      'assets/images/products/lenovo-thinkpad.png',
      'assets/images/products/dell-monitor.png',
      'assets/images/products/apple-homepod.png',
      'assets/images/products/dell-latitude.png',
    ],
    features: [
      'Enterprise-grade security',
      'Long battery life (up to 10 hours)',
      'Spill-resistant keyboard',
      'Extensive connectivity options',
    ],
    label: 'SALE',
    labelColor: '#2db224',
    inStock: true,
    active: true,
    description: 'Powerful and reliable business laptop with excellent performance and durability',
    shortDescription: 'Powerful business laptop with excellent performance',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.6kg', displaySize: '16 inches', resolution: '1920x1080' },
  },
  {
    name: 'HP EliteBook 840 G5 16"',
    brand: 'HP',
    specs: 'Intel Core i5-8350U 16GB RAM 256GB SSD',
    price: 301.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/hp-elitebook.png',
    gallery: 'assets/images/products/hp-elitebook.png',
    inStock: true,
    active: true,
    description: 'Premium business laptop with advanced security features and solid performance',
    shortDescription: 'Premium business laptop with advanced security',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.62kg', displaySize: '16 inches', resolution: '1920x1080' },
  },
  {
    name: 'Dell Latitude 7400 15"',
    brand: 'Dell',
    specs: 'Intel Core i7-8665U 16GB RAM 256GB SSD',
    price: 380.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/dell-latitude.png',
    gallery: 'assets/images/products/dell-latitude.png',
    label: '-25% OFF',
    labelColor: '#2db224',
    inStock: true,
    active: true,
    description: 'Ultra-thin business laptop with exceptional battery life and performance',
    shortDescription: 'Ultra-thin business laptop with exceptional battery life',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.4kg', displaySize: '15 inches', resolution: '1920x1080' },
  },
  {
    name: 'Xiaomi Mi 11 Ultra Max',
    brand: 'Xiaomi',
    specs: '12GB+256GB',
    price: 450.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/xiaomi-mi11.png',
    gallery: 'assets/images/products/xiaomi-mi11.png',
    label: 'NOUVEAU',
    labelColor: '#edd146',
    inStock: true,
    active: true,
    description: 'Flagship smartphone with exceptional camera capabilities and powerful performance',
    shortDescription: 'Selfie periscope for optimal quality',
    categoryName: 'Smartphones',
    extraAttributes: { display: '6.81 inches AMOLED', camera: '50MP+48MP+48MP', battery: '5000mAh' },
  },
  {
    name: 'New Apple Homepod Mini-6',
    brand: 'Apple',
    specs: '100% packed with innovation',
    price: 299.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/apple-homepod.png',
    gallery: 'assets/images/products/apple-homepod.png',
    label: 'NOUVEAU',
    labelColor: '#2da5f3',
    inStock: true,
    active: true,
    description: 'Compact smart speaker with incredible sound quality and seamless integration with Apple ecosystem',
    shortDescription: 'Beautiful new design',
    categoryName: 'Smart Home',
    extraAttributes: { color: 'Space Gray', connectivity: 'WiFi, Bluetooth', assistant: 'Siri' },
  },
  {
    name: 'Lenovo ThinkPad T14 Gen 1 17"',
    brand: 'Lenovo',
    specs: 'Intel Core i5-10310U 16GB RAM 256GB SSD',
    price: 362.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/lenovo-thinkpad.png',
    gallery: 'assets/images/products/lenovo-thinkpad.png',
    galleryImages: [
      'assets/images/products/lenovo-thinkpad.png',
      'assets/images/products/dell-monitor.png',
      'assets/images/products/apple-homepod.png',
      'assets/images/products/dell-latitude.png',
    ],
    features: [
      'Enterprise-grade security',
      'Long battery life (up to 10 hours)',
      'Spill-resistant keyboard',
      'Extensive connectivity options',
    ],
    label: 'SALE',
    labelColor: '#2db224',
    inStock: true,
    active: true,
    description: 'Powerful and reliable business laptop with excellent performance and durability',
    shortDescription: 'Powerful business laptop with excellent performance',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.65kg', displaySize: '17 inches', resolution: '1920x1080' },
  },
  {
    name: 'HP EliteBook 840 G5 17"',
    brand: 'HP',
    specs: 'Intel Core i5-8350U 16GB RAM 256GB SSD',
    price: 301.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/hp-elitebook.png',
    gallery: 'assets/images/products/hp-elitebook.png',
    inStock: true,
    active: true,
    description: 'Premium business laptop with advanced security features and solid performance',
    shortDescription: 'Premium business laptop with advanced security',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.67kg', displaySize: '17 inches', resolution: '1920x1080' },
  },
  {
    name: 'Dell Latitude 7400 14" Elite',
    brand: 'Dell',
    specs: 'Intel Core i7-8665U 16GB RAM 256GB SSD',
    price: 380.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/dell-latitude.png',
    gallery: 'assets/images/products/dell-latitude.png',
    label: '-25% OFF',
    labelColor: '#2db224',
    inStock: true,
    active: true,
    description: 'Ultra-thin business laptop with exceptional battery life and performance',
    shortDescription: 'Ultra-thin business laptop with exceptional battery life',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.36kg', displaySize: '14 inches', resolution: '1920x1080' },
  },
  {
    name: 'Xiaomi Mi 11 Ultra Premium',
    brand: 'Xiaomi',
    specs: '12GB+256GB',
    price: 450.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/xiaomi-mi11.png',
    gallery: 'assets/images/products/xiaomi-mi11.png',
    label: 'NOUVEAU',
    labelColor: '#edd146',
    inStock: true,
    active: true,
    description: 'Flagship smartphone with exceptional camera capabilities and powerful performance',
    shortDescription: 'Selfie periscope for optimal quality',
    categoryName: 'Smartphones',
    extraAttributes: { display: '6.81 inches AMOLED', camera: '50MP+48MP+48MP', battery: '5000mAh' },
  },
  {
    name: 'New Apple Homepod Mini-5',
    brand: 'Apple',
    specs: '100% packed with innovation',
    price: 299.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/apple-homepod.png',
    gallery: 'assets/images/products/apple-homepod.png',
    label: 'NOUVEAU',
    labelColor: '#2da5f3',
    inStock: true,
    active: true,
    description: 'Compact smart speaker with incredible sound quality and seamless integration with Apple ecosystem',
    shortDescription: 'Beautiful new design',
    categoryName: 'Smart Home',
    extraAttributes: { color: 'Blue', connectivity: 'WiFi, Bluetooth', assistant: 'Siri' },
  },
  {
    name: 'New Apple Homepod Mini-4',
    brand: 'Apple',
    specs: '100% packed with innovation',
    price: 299.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/apple-homepod.png',
    gallery: 'assets/images/products/apple-homepod.png',
    label: 'NOUVEAU',
    labelColor: '#2da5f3',
    inStock: true,
    active: true,
    description: 'Compact smart speaker with incredible sound quality and seamless integration with Apple ecosystem',
    shortDescription: 'Beautiful new design',
    categoryName: 'Smart Home',
    extraAttributes: { color: 'Yellow', connectivity: 'WiFi, Bluetooth', assistant: 'Siri' },
  },
  {
    name: 'Lenovo ThinkPad T14 Gen 1 141"',
    brand: 'Lenovo',
    specs: 'Intel Core i5-10310U 16GB RAM 256GB SSD',
    price: 362.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/lenovo-thinkpad.png',
    gallery: 'assets/images/products/lenovo-thinkpad.png',
    galleryImages: [
      'assets/images/products/lenovo-thinkpad.png',
      'assets/images/products/dell-monitor.png',
      'assets/images/products/apple-homepod.png',
      'assets/images/products/dell-latitude.png',
    ],
    features: [
      'Enterprise-grade security',
      'Long battery life (up to 10 hours)',
      'Spill-resistant keyboard',
      'Extensive connectivity options',
    ],
    label: 'SALE',
    labelColor: '#2db224',
    inStock: true,
    active: true,
    description: 'Powerful and reliable business laptop with excellent performance and durability',
    shortDescription: 'Powerful business laptop with excellent performance',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.47kg', displaySize: '14 inches', resolution: '1920x1080' },
  },
  {
    name: 'HP EliteBook 840 G5 142"',
    brand: 'HP',
    specs: 'Intel Core i5-8350U 16GB RAM 256GB SSD',
    price: 301.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/hp-elitebook.png',
    gallery: 'assets/images/products/hp-elitebook.png',
    inStock: true,
    active: true,
    description: 'Premium business laptop with advanced security features and solid performance',
    shortDescription: 'Premium business laptop with advanced security',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.48kg', displaySize: '14 inches', resolution: '1920x1080' },
  },
  {
    name: 'Dell Latitude 7400 143"',
    brand: 'Dell',
    specs: 'Intel Core i7-8665U 16GB RAM 256GB SSD',
    price: 380.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/dell-latitude.png',
    gallery: 'assets/images/products/dell-latitude.png',
    label: '-25% OFF',
    labelColor: '#2db224',
    inStock: true,
    active: true,
    description: 'Ultra-thin business laptop with exceptional battery life and performance',
    shortDescription: 'Ultra-thin business laptop with exceptional battery life',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.36kg', displaySize: '14 inches', resolution: '1920x1080' },
  },
  {
    name: 'Xiaomi Mi 11 Ultra4',
    brand: 'Xiaomi',
    specs: '12GB+256GB',
    price: 450.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/xiaomi-mi11.png',
    gallery: 'assets/images/products/xiaomi-mi11.png',
    label: 'NOUVEAU',
    labelColor: '#edd146',
    inStock: true,
    active: true,
    description: 'Flagship smartphone with exceptional camera capabilities and powerful performance',
    shortDescription: 'Selfie periscope for optimal quality',
    categoryName: 'Smartphones',
    extraAttributes: { display: '6.81 inches AMOLED', camera: '50MP+48MP+48MP', battery: '5000mAh' },
  },
  {
    name: 'New Apple Homepod Mini-85',
    brand: 'Apple',
    specs: '100% packed with innovation',
    price: 299.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/apple-homepod.png',
    gallery: 'assets/images/products/apple-homepod.png',
    label: 'NOUVEAU',
    labelColor: '#2da5f3',
    inStock: true,
    active: true,
    description: 'Compact smart speaker with incredible sound quality and seamless integration with Apple ecosystem',
    shortDescription: 'Beautiful new design',
    categoryName: 'Smart Home',
    extraAttributes: { color: 'White', connectivity: 'WiFi, Bluetooth', assistant: 'Siri' },
  },
  {
    name: 'Apple iPhone 13 Pro6',
    brand: 'Apple',
    specs: '6GB+256GB',
    price: 799.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/iphone13.png',
    gallery: 'assets/images/products/iphone13.png',
    inStock: true,
    active: true,
    description: 'Premium smartphone with advanced camera system and powerful A15 Bionic chip',
    shortDescription: 'Premium smartphone with advanced camera system',
    categoryName: 'Smartphones',
    extraAttributes: { display: '6.1 inches Super Retina XDR', camera: '12MP+12MP+12MP', battery: '3095mAh' },
  },
  {
    name: 'Samsung Galaxy S21 Ultra7',
    brand: 'Samsung',
    specs: '12GB+256GB',
    price: 749.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/samsung-s21.png',
    gallery: 'assets/images/products/samsung-s21.png',
    label: '-10% OFF',
    labelColor: '#edd146',
    inStock: true,
    active: true,
    description: 'Flagship smartphone with 108MP camera and 120Hz adaptive display',
    shortDescription: 'Flagship smartphone with 108MP camera',
    categoryName: 'Smartphones',
    extraAttributes: { display: '6.8 inches Dynamic AMOLED 2X', camera: '108MP+10MP+10MP+12MP', battery: '5000mAh' },
  },
  {
    name: 'Google Pixel 6 Pro8',
    brand: 'Google',
    specs: '12GB+128GB',
    price: 699.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/google-pixel6.png',
    gallery: 'assets/images/products/google-pixel6.png',
    inStock: true,
    active: true,
    description: 'Google flagship with exceptional camera capabilities and the new Tensor chip',
    shortDescription: 'Google flagship with exceptional camera capabilities',
    categoryName: 'Smartphones',
    extraAttributes: { display: '6.7 inches LTPO OLED', camera: '50MP+48MP+12MP', battery: '5003mAh' },
  },
  {
    name: 'Lenovo ThinkPad T14 Gen 1 159"',
    brand: 'Lenovo',
    specs: 'Intel Core i5-10310U 16GB RAM 256GB SSD',
    price: 362.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/lenovo-thinkpad.png',
    gallery: 'assets/images/products/lenovo-thinkpad.png',
    galleryImages: [
      'assets/images/products/lenovo-thinkpad.png',
      'assets/images/products/dell-monitor.png',
      'assets/images/products/apple-homepod.png',
      'assets/images/products/dell-latitude.png',
    ],
    features: [
      'Enterprise-grade security',
      'Long battery life (up to 10 hours)',
      'Spill-resistant keyboard',
      'Extensive connectivity options',
    ],
    label: 'SALE',
    labelColor: '#2db224',
    inStock: true,
    active: true,
    description: 'Powerful and reliable business laptop with excellent performance and durability',
    shortDescription: 'Powerful business laptop with excellent performance',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.51kg', displaySize: '15 inches', resolution: '1920x1080' },
  },
  {
    name: 'HP EliteBook 840 G5 150"',
    brand: 'HP',
    specs: 'Intel Core i5-8350U 16GB RAM 256GB SSD',
    price: 301.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/hp-elitebook.png',
    gallery: 'assets/images/products/hp-elitebook.png',
    inStock: true,
    active: true,
    description: 'Premium business laptop with advanced security features and solid performance',
    shortDescription: 'Premium business laptop with advanced security',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.51kg', displaySize: '15 inches', resolution: '1920x1080' },
  },
  {
    name: 'Dell Latitude 7400 151"',
    brand: 'Dell',
    specs: 'Intel Core i7-8665U 16GB RAM 256GB SSD',
    price: 380.0,
    currency: 'XAF',
    imageUrl: 'assets/images/products/dell-latitude.png',
    gallery: 'assets/images/products/dell-latitude.png',
    label: '-25% OFF',
    labelColor: '#2db224',
    inStock: true,
    active: true,
    description: 'Ultra-thin business laptop with exceptional battery life and performance',
    shortDescription: 'Ultra-thin business laptop with exceptional battery life',
    categoryName: 'Laptops',
    extraAttributes: { weight: '1.41kg', displaySize: '15 inches', resolution: '1920x1080' },
  },
];

export class CreateProducts implements Seeder {
  constructor(private readonly filesService: FilesService) {}

  async run(): Promise<void> {
    const productRepository = getRepository(Product);
    const categoryRepository = getRepository(Category);
    const storeRepository = getRepository(Store);
    const authRepository = getRepository(Auth);

    // Find the existing admin user (created by create-admin-store.seed.ts)
    const adminAuth = await authRepository.findOne({
      where: { email: 'jospen.wolongwo@hellocomputing.tech' },
    });

    if (!adminAuth?.user) {
      console.error('Admin user not found! Please run the admin store seeder first.');

      return;
    }

    // Find the store
    const store = await storeRepository.findOne({ where: { name: 'Hello Hardware' } });

    if (!store) {
      console.error('Store not found! Please run the admin store seeder first.');

      return;
    }

    // Predefined categories with descriptions
    const predefinedCategories = [
      { name: 'Laptops', description: 'High-performance laptops for work and personal use' },
      { name: 'Telephones', description: 'Smartphones and mobile phones' },
      { name: 'Tablets', description: 'Portable tablet devices' },
      { name: 'Ecran Plat', description: 'Flat screen monitors and displays' },
    ];

    // Create categories if they don't exist
    const categories = new Map<string, Category>();
    for (const categoryData of predefinedCategories) {
      let category = await categoryRepository.findOne({
        where: { name: categoryData.name, store },
      });

      if (!category) {
        category = new Category();
        category.name = categoryData.name;
        category.description = categoryData.description;
        category.store = store;
        await categoryRepository.save(category);
        console.log(`Created category: ${categoryData.name}`);
      }

      categories.set(categoryData.name, category);
    }

    // Get unique category names from products
    const productCategoryNames = [...new Set(PRODUCTS.map((p) => p.categoryName))];

    // Validate that all product categories exist
    for (const name of productCategoryNames) {
      if (!categories.has(name)) {
        console.warn(`Warning: Product category '${name}' not in predefined categories`);
      }
    }

    // Check for existing products to avoid duplicates
    for (const productData of PRODUCTS) {
      const { categoryName, ...data } = productData;

      // Check if product already exists
      const existingProduct = await productRepository.findOne({
        where: { name: data.name, brand: data.brand },
      });

      if (!existingProduct) {
        const category = categories.get(categoryName);
        // Skip if category doesn't exist
        if (category) {
          const product = new Product();
          Object.assign(product, data);
          product.category = category;

          // Calculate min and max price from the seed data
          product.minPrice = product.price * 0.9; // Example calculation
          product.maxPrice = product.price * 1.2; // Example calculation

          await productRepository.save(product);
          console.log(`Created product: ${data.name}`);
        } else {
          console.log(`Skipping product ${data.name} as category ${categoryName} was not found`);
        }
      } else {
        console.log(`Product already exists: ${data.name}`);
      }
    }
  }
}
